sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
  - secure: l3u51OCgKe54YItziQRsXUm7VCbChYyu17q+DS24eOxTn4F4QHDDDgbpVe+uQ8s0ILhMm5JUXiadOnaEkZVlJ4+S42f4c8jI40cSsYCb+pWrYhLCoPwLLggzlkVQpt00y0iekHvA2h6EyySAuHMIGnuRoO2wMkp2+HNAmzY4DhokeFYAHneDsV548syuUkq+fjZQ6R2t2BJ5B8jQ5gQPUTGlnVdQvKtuJMgcKxxXnreP2PcXgA0SVDQBaqaH4MQ/QTYFV3jFFrDGZRFf/WcAL7DIltyfKL7sorqyOkJU2GNpsjw8KPC1rvhDgPOXVyuIM1fXC1OK57b6lSVkExv8exEBWmQPJ+FOs8JsnbOTZNwCdedz3oKre7yaY5J64QtyTAXYYvD190l7Gj7b38E6MX5Tm8RqPYN8DiQSOTqresqzvp3DfW5DOIL2RVAOYk93EhUsvfKXaK80FF76j8wAUA5qWHon0TWm+mg6nAp/6Xn2wLwkWFNHIyTmWsyRr8TuyyjVoyr+G+OJg1+0t0Fip/E1RyjBbZDloKMAq7FTSZiu4nys6xwSLM1t/nHBtXONLi2u3yD7MrA5mvA6kdBldOnpLUQwiu28ItNK9NY3JsJcX3dh301S5dCM+RJ5RKBdVm+CPabVj33tti5HLUbbQoFEJXotVpDqHHVcxPUlL8Q=
branches:
  only:
  - master
